version: 2.1
jobs:
  Hello-World:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello world'
            echo 'This is the delivery pipeline'
  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Getting the Code
          command: |
            ls -al
            echo '^^^The files in your repo^^^'
  Using-Node:
    docker:
      - image: cimg/node:17.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v
  Now-Complete:
      docker:
        - image: alpine:3.15
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
      steps:
        - run:
            name: Approval Now-Complete
            command: |
              echo 'The work is now complete.'
workflows:
  Example-Workflow:
    jobs:
    - Hello-World
    - Fetch-Code:
        requires:
          - Hello-World
    - Using-Node:
        requires:
          - Fetch-Code
    - Hold-for-Approval:
        type: approval
        requires:
          - Using-Node
          - Fetch-COde
    - Now-Complete:
        requires:
        - Hold-for-Approval
